Repository pyapp-kit/ndv, pull requests merged in 2025-02, with the labels that each got.

#87 refactor: Pass LUTModel to LUTView
  pyproject.toml
  src/ndv/controllers/_array_viewer.py
  src/ndv/controllers/_channel_controller.py
  src/ndv/models/_lut_model.py
  src/ndv/v1/_old_viewer.py
  src/ndv/v1/_qt/_lut_control.py
  src/ndv/views/_jupyter/_array_view.py
  src/ndv/views/_pygfx/_array_canvas.py
  src/ndv/views/_pygfx/_histogram.py
  src/ndv/views/_qt/_array_view.py
  src/ndv/views/_vispy/_array_canvas.py
  src/ndv/views/_vispy/_histogram.py
  src/ndv/views/_wx/_array_view.py
  src/ndv/views/_wx/range_slider.py
  src/ndv/views/bases/_graphics/_canvas_elements.py
  src/ndv/views/bases/_lut_view.py
  tests/test_controller.py
  tests/views/_jupyter/__init__.py
  tests/views/_jupyter/test_lut_view.py
  tests/views/_qt/__init__.py
  tests/views/_qt/test_lut_view.py
  tests/views/_wx/__init__.py
  tests/views/_wx/test_lut_view.py
Labels: enhancement

#137 test: skip ubuntu-vispy-pyside-3.12
  .github/workflows/ci.yml
Labels: tests

#136 feat: add `call_later` (public) and `process_events` (private) to the NDVApp API
  src/ndv/views/__init__.py
  src/ndv/views/_app.py
  src/ndv/views/_qt/_app.py
  src/ndv/views/_wx/_app.py
  src/ndv/views/bases/_app.py
Labels: enhancement

#139 feat: add widget visibility options to ArrayViewerModel
  src/ndv/controllers/_array_viewer.py
  src/ndv/models/_viewer_model.py
  src/ndv/views/_jupyter/_array_view.py
  src/ndv/views/_qt/_array_view.py
  src/ndv/views/_wx/_array_view.py
  src/ndv/views/bases/_array_view.py
  tests/conftest.py
  tests/views/_jupyter/test_array_view.py
  tests/views/_qt/conftest.py
  tests/views/_qt/test_array_view.py
  tests/views/_qt/test_lut_view.py
  tests/views/_wx/test_array_view.py
  tests/views/_wx/test_lut_view.py
Labels: enhancement

#142 Purge v1
  src/ndv/v1/__init__.py
  src/ndv/v1/_old_data_wrapper.py
  src/ndv/v1/_old_viewer.py
  src/ndv/v1/_qt/__init__.py
  src/ndv/v1/_qt/_components.py
  src/ndv/v1/_qt/_dims_slider.py
  src/ndv/v1/_qt/_lut_control.py
  src/ndv/v1/_util.py
  tests/v1/test_v1_viewer.py
Labels: bug
