Repository pyapp-kit/ndv, pull requests merged in 2025-01, with the labels that each got.

#101 docs: minor installation fixes & cleanup
  docs/js/install-table.js
Labels: documentation

#102 feat: add reset zoom button to jupyter
  examples/notebook.ipynb
  src/ndv/views/_jupyter/_array_view.py
  src/ndv/views/_wx/_array_view.py
Labels: enhancement

#92 feat: adding back async
  docs/env_var.md
  examples/notebook.ipynb
  examples/zarr_arr.py
  pyproject.toml
  src/ndv/controllers/_array_viewer.py
  src/ndv/data.py
  src/ndv/models/_data_display_model.py
  src/ndv/views/_app.py
  src/ndv/views/_jupyter/_array_view.py
  src/ndv/views/_qt/_array_view.py
  src/ndv/views/_qt/_main_thread.py
  src/ndv/views/_qt/spin.gif
  src/ndv/views/_resources/spin.gif
  src/ndv/views/_wx/_array_view.py
  src/ndv/views/_wx/_main_thread.py
  src/ndv/views/bases/_array_view.py
  tests/test_controller.py
Labels: enhancement

#105 Pygfx histogram v2
  pyproject.toml
  src/ndv/views/_app.py
  src/ndv/views/_pygfx/_histogram.py
  tests/conftest.py
  tests/test_controller.py
Labels: enhancement

#120 fix: hide sliders for singleton axes
  src/ndv/controllers/_array_viewer.py
  tests/test_controller.py
Labels: bug

#123 docs: Add a set of examples in `cookbook`
  docs/cookbook/embedding.md
  examples/cookbook/microscope_dashboard.py
  examples/cookbook/multi_ndv.py
  examples/cookbook/ndv_embedded.py
  mkdocs.yml
Labels: documentation

#124 docs: make all scripts pep 723 compliant
  examples/README.md
  examples/dask_arr.py
  examples/notebook.ipynb
  examples/numpy_arr.py
  examples/pyopencl_arr.py
  examples/sparse_arr.py
  examples/tensorstore_arr.py
  examples/torch_arr.py
  examples/xarray_arr.py
  examples/zarr_arr.py
Labels: documentation
